README.md, src/main/java/io/github/jhipster/online/web/rest/GitResource.java
Here is the GitLab part of the readme.
@jdubois I'm not sure about the bot stuff tho. In you part you wrote:
```
In order for JHipster Online to use that bot, it will need its OAuth token: log in as the "JHipster Bot" user, and go to 
"Settings > Developer Settings > Personal access tokens" and generate a new token.
```
But how are you supposed to `log in as the "JHipster Bot"`? I don't understand. 
And for the GitLab bot, is it implemented? It doesn't seem to be.
=> gitlab configuration 'how to'

pom.xml
Fix #63
Thanks @deepu105 for the suggestion
I analyzed the `mvn dependency:tree`:
```
[INFO] +- com.google.cloud.sql:mysql-socket-factory:jar:1.0.3:compile
[INFO] |  \- com.google.cloud.sql:mysql-socket-factory-core:jar:1.0.3:compile
[INFO] |     \- com.google.apis:google-api-services-sqladmin:jar:v1beta4-rev25-1.22.0:compile
[INFO] |        \- com.google.api-client:google-api-client:jar:1.22.0:compile
[INFO] |           +- com.google.oauth-client:google-oauth-client:jar:1.22.0:compile
[INFO] |           |  \- com.google.http-client:google-http-client:jar:1.22.0:compile
[INFO] |           +- com.google.http-client:google-http-client-jackson2:jar:1.22.0:compile
[INFO] |           \- com.google.guava:guava-jdk5:jar:17.0:compile
```
When you package with `prod` profile, it will not contain …
=> Add profile gcp

README.md
Some small shell command alignment in README.md. The first three commands in the [quick start guide](https://github.com/jhipster/jhipster-online#quick-start-guide) isn't shown with correct formatting. :smile:
=> Add proper shell command alignment to the README.md file

webpack/webpack.common.js
This adds es2015 bundling back into the webpack configuration. We removed it previously due to Firefox bug effecting Firefox versions < 77
Related to https://github.com/jhipster/generator-jhipster/issues/11566 and https://github.com/jhipster/generator-jhipster/pull/11619
=> Add es2015 Bundling Back into webpack.common.js

src/main/java/io/github/jhipster/online/service/enums/CiCdTool.java, src/main/webapp/app/home/ci-cd/ci-cd.component.html
This adds the GitHub Actions and CircleCI to the list of continuous integration options.
Fixes https://github.com/jhipster/jhipster-online/issues/163
=> Add GitHub Actions and CircleCI for Continuous Integration

.github/workflows/github-ci.yml
This adds SonarCloud analysis to CI; the analysis should be triggered for PRs as well. 
Resolves https://github.com/jhipster/jhipster-online/issues/202
=> Add SonarCloud Analysis to CI

.github/workflows/github-ci.yml
This fixes the problem with Sonar analysis not being triggered in fork branches correctly.
=> Enable SonarCloud only on Push (disable for Pull Requests)

src/main/java/io/github/jhipster/online/web/rest/JdlResource.java
This is not a real vulnerability I think as we randomly generate the ID. There's no way the user can insert or manipulate the id here.
Related to https://github.com/jhipster/jhipster-online/issues/209
=> Fix False Positive by Sonar

src/main/java/io/github/jhipster/online/service/JHipsterService.java
This adds a non-blocking input.ready() call for BufferReader.readline() as I've noticed that there's a possibility for this to block when reading the next line. 
Reference: https://stackoverflow.com/questions/15521352/bufferedreader-readline-blocks
Related to https://github.com/jhipster/jhipster-online/issues/184
=> Add Non-blocking input.ready() call for BufferReader

.dockerignore, .github/workflows/deploy.yml, Dockerfile, README.md, app.yaml, pom.xml, src/main/resources/config/application-gcp.yml, src/main/resources/config/application-prod.yml
This basically takes away most of the developer effort in deploying jhipster-online, and automates the deployment using CloudRun + GitHub Actions.
Fixes https://github.com/jhipster/jhipster-online/issues/172
=> Add Auto Deployments with CloudRun + GitHub Actions

.github/workflows/deploy.yml, app.yaml, pom.xml, src/main/java/io/github/jhipster/online/service/JHipsterService.java, src/main/resources/config/application-gcp.yml
This changes the database connection without using the Spring GCP dependencies. The Spring GCP dependency is unnecessary and was introduced when we were testing Cloud Run. The database connection can be simplified as in this PR. 
Related to https://github.com/jhipster/jhipster-online/issues/230
=> Use a simplified database connection

src/main/java/io/github/jhipster/online/service/CiCdService.java, src/main/java/io/github/jhipster/online/service/JdlService.java, src/main/java/io/github/jhipster/online/service/YoRCService.java
Hey folks,
just changed a few lines where exceptions where printed by the `printStackTrace`-method and not by the provided logger.
Thought that this would be an improvement to issue #209.
=> Print Exceptions via Logger Instead of Using printStackTrace

src/main/webapp/app/home/ci-cd/ci-cd.component.ts, src/main/webapp/app/home/git/git.component.ts, src/main/webapp/app/home/jdl-metadata/jdl-studio.component.ts, src/main/webapp/app/shared/git-provider/git-provider.component.ts
fixes opening a page directly and logging in without remember-me
Similar to https://github.com/jhipster/jhipster-online/issues/76
- Log Out
- Open one of the following pages in a new tab/window and login WITHOUT remember-me:
- https://start.jhipster.tech/git
- https://start.jhipster.tech/ci-cd
The page will look different than if you were authenticated and navigate to the page.
CI Page - [Broken](https://user-images.githubusercontent.com/4294623/94944128-cb7d4980-04a6-11eb-9787-a1eb6e965fff.png) - [Working](https://user-images.githubusercontent.com/4294623/94944122-cae4b300-04a6-11eb-9d63-255c50583498.png)
Git Page - [Broken](https://user-images.githubusercontent.com/4294623/94944129-cc15e000-04a6-11eb-824b-5637bd3bfd30.png) - [Working](https://user-images.githubusercontent.com/4294623/949 …
=> Fix git config update

src/main/java/io/github/jhipster/online/service/JHipsterService.java, src/test/java/io/github/jhipster/online/service/JHipsterServiceTest.java
=> Improve Test Coverage - JHipsterService

src/main/java/io/github/jhipster/online/service/GitService.java
This renames the default branch of the generated project to main
Resolves https://github.com/jhipster/jhipster-online/issues/258
=> Change the generated projects default branch name to main

src/main/webapp/app/entities/statistics/statistics.component.html, src/main/webapp/app/home/ci-cd/ci-cd.component.html, src/main/webapp/app/home/generator/generator.component.html, src/main/webapp/app/home/home.component.html
Hey @SudharakaP, Here are the changes as per our discussion in #237. Kindly check these out.
Resolves #237
=> UI Improvements

src/main/webapp/app/core/auth/auth-jwt.service.ts
apply fix from https://github.com/jhipster/generator-jhipster/pull/12610
possibly related to https://github.com/jhipster/jhipster-online/issues/262 (after authentication success, a second 401 was received, guessing it used the old token)
Steps to reproduce issue:
- Login with remember-me
- Make JWT token invalid by adding random letters to localStorage's `jhi-authenticationtoken` value (in browser dev tools)
- If the token expired from time, the same issue would happen
- Login without remember-me
- Authentication fails - it uses the invalid localStorage token over the sessionStorage token
=> Clear old tokens after successful login

src/main/java/io/github/jhipster/online/service/GithubService.java, src/main/java/io/github/jhipster/online/service/GitlabService.java
As per the following comment by @ruddell; 
https://github.com/jhipster/jhipster-online/issues/258#issuecomment-725646522
this pull request adds support for backward compatibility of existing repos with `master` branch. Otherwise it seems that when trying to create pull requests it will give an error due to not having the `main` branch.
=> Use Default Branch when creating PRs

.github/workflows/copyright-update.yml
This adds support to auto update copyright headers every year through a GitHub Action. 😄 
Resolved https://github.com/jhipster/jhipster-online/issues/276
=> Add Support to Auto Update Copyright Headers

src/main/java/io/github/jhipster/online/service/JHipsterService.java, src/test/java/io/github/jhipster/online/service/JHipsterServiceTest.java
The `force-insights` option needs to be supported and I believe there's a regression in the generator regarding this. Ideally we should fix this in the generator. I've opened a PR there. 
Related https://github.com/jhipster/jhipster-online/pull/288
Related https://github.com/jhipster/generator-jhipster/pull/14485
=> Add force-insights back to jhipster-online

src/main/webapp/app/home/welcome/welcome.component.html
Add create application card on homepage to redirect users to create
application anonymously
The homepage appears as below after this change:-
Fix #305
=> Add Create application card

.github/workflows/docker.yml, Dockerfile
Reuse JHipster docker image.
It has everything required to run jhipster already.
=> Switch docker base image to jhipster image.

src/main/java/io/github/jhipster/online/domain/deserializer/YoRCDeserializer.java, src/test/java/io/github/jhipster/online/web/rest/StatisticsResourceIntTest.java
This fixes the bug where the request to save yorc statistics fails when
a `creationTime` was provided in the `generator-jhipster` part of the
entry payload. The issue is that `Instant.parse()` was called with a
timestamp while it only accepts an ISO formatted instant.
Fix jhipster/generator-jhipster#18238
=> fix statistics creation when creationTime is provided

src/main/webapp/app/home/generator/generator.component.html
We might need to adjust the Cypress and Protractor conditionals to account for micro frontends.
Fixes https://github.com/jhipster/generator-jhipster/issues/19647.
=> Add Cypress to testing options

src/main/java/io/github/jhipster/online/security/jwt/TokenProvider.java, src/main/webapp/app/account/password/password-strength-bar.component.ts, src/main/webapp/app/admin/configuration/configuration.component.ts, src/main/webapp/app/blocks/interceptor/auth.interceptor.ts, src/main/webapp/app/core/auth/account.service.ts, src/main/webapp/app/home/ci-cd/ci-cd.component.ts, src/main/webapp/app/home/generator/generator.component.ts, src/main/webapp/app/home/generator/jhipster.configuration.model.ts, src/main/webapp/app/home/git/git.component.ts, src/main/webapp/app/home/jdl-metadata/jdl-studio.component.ts, src/main/webapp/app/shared/git-provider/git-provider.component.ts, src/main/webapp/app/shared/model/yo-rc.model.ts
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster_jhipster-online
Before:
=> Sonar issues

src/test/java/io/github/jhipster/online/domain/enums/EntityStatColumnTest.java, src/test/java/io/github/jhipster/online/domain/enums/SubGenEventTypeTest.java, src/test/java/io/github/jhipster/online/service/enums/CiCdToolTest.java
`Task Description:`
This PR is an attempt to increase some code coverage percentage.
I added a few test cases, which made some improvement in the code coverage i.e. 78% -> 80%.
`Issue Id`:
https://github.com/jhipster/jhipster-online/issues/213
`Screenshots:`
| Earlier | Now |
--- | ---
|<img width="1440" alt="before_change_0 1" src="https://github.com/jhipster/jhipster-online/assets/19683035/2e68d2f9-e248-43ed-bb92-983ac8aa2d81">|<img width="1440" alt="overall_change_6" src="https://github.com/jhipster/jhipster-online/assets/19683035/7737f717-18ab-4847-baaf-d755a04b1001">|
`Affected Files:`
- src/main/java/io/github/jhipster/online/domain/enums/EntityStatColumnTest.java
- src/main/java/io/github/jhipster/online/domain/enums/SubGenEventTypeTest.java
- …
=> Improve Test Coverage - EntityStatColumn, CiCdToolTest, SubGenEventTypeTest

pom.xml, src/test/resources/config/application.yml
CI/CD has been failing for some time because we use "mysql:8" without specifying the minor/patch versions, and there has been a bug introduced since MySQL 8.3.0.
See https://github.com/testcontainers/testcontainers-java/issues/8130
=> Fix testcontainers + MySQL bug

src/main/webapp/app/home/azure-generator/azure-generator.component.html, src/main/webapp/app/home/ci-cd/ci-cd.output.component.html, src/main/webapp/app/home/generator/generator.output.component.html, src/main/webapp/app/home/jdl-metadata/jdl.output.component.html
Fix 13 security hotspots https://sonarcloud.io/project/security_hotspots?id=jhipster_jhipster-online&tab=code
=> Sonar: Fix 'Make sure not using rel=noopener is safe here'
