Dockerfile
Fix https://github.com/jhipster/jhipster-online/issues/53
=> Add Docker Hub image

src/main/webapp/app/home/statistics/statistics.component.html, src/main/webapp/app/home/statistics/statistics.component.ts, src/main/webapp/app/home/statistics/statistics.scss
fixed loading data problem when toggling fullscreen
added specific tabs to client framework and buildtool sections
=> Fixes on statistics fullScreen view

src/main/webapp/app/entities/statistics/statistics.component.ts, src/main/webapp/app/entities/statistics/statistics.model.ts, src/main/webapp/app/entities/statistics/statistics.options.ts
Fixed prettify date and superimposing charts when going from Angular VS React select to General overview select
=> Fixed chart display problems

src/main/java/io/github/jhipster/online/service/CiCdService.java, src/main/java/io/github/jhipster/online/service/JHipsterService.java, src/main/java/io/github/jhipster/online/service/enums/CiCdTool.java, src/main/java/io/github/jhipster/online/web/rest/CiCdResource.java, src/main/webapp/app/home/ci-cd/ci-cd.component.html
Refactoring the CI/CD options to a better experience in add another tool.
This resolve #80
@pascalgrimaud You can review the Azure description? I wrote but I don't know it's correct
=> Adding Gitlab and Azure to CI/CD options

src/main/java/io/github/jhipster/online/service/CiCdService.java, src/main/java/io/github/jhipster/online/service/GitlabService.java
I fix the merge url for Gitlab when using CI/CD feature.
That correct the others place when using the number how PR id.
=> Fix gitlab merge url

src/main/webapp/app/home/generator/generator.component.html
=> Remove karma ref from generator form

src/main/webapp/app/shared/git-provider/git-provider.component.ts
fix #76
Better late than never I guess. :sweat_smile:
As the title suggests, the component wasn't properly being refreshed.
=> Fix git provider component update

pom.xml, src/test/java/io/github/jhipster/online/config/AsyncConfiguration.java, src/test/java/io/github/jhipster/online/config/WebConfigurerTest.java, src/test/java/io/github/jhipster/online/repository/CustomAuditEventRepositoryIntTest.java, src/test/java/io/github/jhipster/online/security/DomainUserDetailsServiceIntTest.java, src/test/java/io/github/jhipster/online/security/SecurityUtilsUnitTest.java, src/test/java/io/github/jhipster/online/security/jwt/JWTFilterTest.java, src/test/java/io/github/jhipster/online/security/jwt/TokenProviderTest.java, src/test/java/io/github/jhipster/online/service/GeneratorIdentityServiceTest.java, src/test/java/io/github/jhipster/online/service/MailServiceIntTest.java, src/test/java/io/github/jhipster/online/service/UserServiceIntTest.java, src/test/java/io/github/jhipster/online/service/enums/TemporalValueTypeTest.java, src/test/java/io/github/jhipster/online/service/util/DateUtilTest.java, src/test/java/io/github/jhipster/online/service/yorc/YoRCServiceChoicesIntTest.java, src/test/java/io/github/jhipster/online/service/yorc/YoRCServiceCountsIntTest.java, src/test/java/io/github/jhipster/online/web/rest/AccountResourceIntTest.java, src/test/java/io/github/jhipster/online/web/rest/AuditResourceIntTest.java, src/test/java/io/github/jhipster/online/web/rest/EntityStatsResourceIntTest.java, src/test/java/io/github/jhipster/online/web/rest/GeneratorIdentityResourceIntTest.java, src/test/java/io/github/jhipster/online/web/rest/GitResourceIntTest.java, src/test/java/io/github/jhipster/online/web/rest/LogsResourceIntTest.java, src/test/java/io/github/jhipster/online/web/rest/StatisticsResourceIntTest.java, src/test/java/io/github/jhipster/online/web/rest/SubGenEventResourceIntTest.java, src/test/java/io/github/jhipster/online/web/rest/TestUtil.java, src/test/java/io/github/jhipster/online/web/rest/UserJWTControllerIntTest.java, src/test/java/io/github/jhipster/online/web/rest/UserResourceIntTest.java, src/test/java/io/github/jhipster/online/web/rest/YoRCResourceIntTest.java, src/test/java/io/github/jhipster/online/web/rest/errors/ExceptionTranslatorIntTest.java, src/test/java/io/github/jhipster/online/web/rest/errors/ExceptionTranslatorTestController.java, src/test/java/io/github/jhipster/online/web/rest/util/PaginationUtilUnitTest.java
Fix #107
- Please make sure the below checklist is followed for Pull Requests.
=> Upgrade to JUnit 5

README.md, azure-pipelines.yml
Fix #109
We also need to init the pipeline on Azure.
=> Azure pipelines migration

src/main/webapp/app/home/generator/generator.component.html, src/main/webapp/app/home/generator/generator.component.ts, src/main/webapp/app/home/generator/jhipster.configuration.model.ts
- Add missing languages
- Change name and value for Indonesia
- Use same default values than CLI generator
- Set packageName to 'com.mycompany.myapp', is that ok ?
- Remove UI for useSass option as it is now always true
=> use same default as CLI, add & fix languages

src/main/webapp/app/entities/statistics/statistics.component.ts, src/main/webapp/app/entities/statistics/statistics.options.ts, src/main/webapp/app/entities/statistics/statistics.utils.ts
Display only available options
=> Improve charts display

src/main/webapp/app/home/generator/generator.component.html
Added Caffeine cache option
Related to: https://github.com/jhipster/generator-jhipster/issues/9351
=> add Caffeine cache option

src/main/webapp/app/entities/statistics/statistics.component.html
=> Typo: anonymously

azure-pipelines.yml
Related to https://github.com/jhipster/generator-jhipster/pull/11048
=> Update Copywrite Headers for 2020

.github/workflows/github-ci.yml
I created github-ci.yml to implement github action.
I keep the same java (8) and node (10.16.3) version for this CI.
=> Add github-ci.yml to set-up ci on Github action

.github/workflows/github-ci.yml
This PR completes the #154 with new `actions/checkout` version.
To be more consistent with generator project I also updated the node version.
=> Update actions and node version on .yml file

src/main/java/io/github/jhipster/online/repository/JdlMetadataRepository.java, src/main/java/io/github/jhipster/online/service/JdlMetadataService.java, src/main/java/io/github/jhipster/online/web/rest/JdlMetadataResource.java, src/main/webapp/app/home/jdl-metadata/jdl-metadata.component.html, src/main/webapp/app/home/jdl-metadata/jdl-metadata.component.ts, src/main/webapp/app/vendor.ts
=> Add jdl sorting

src/main/java/io/github/jhipster/online/service/JHipsterService.java, src/main/webapp/app/home/generator/generator.component.html
Just adding neo4j to selections
I guess this need a new release of the main generator, which we must integrate afterwards.
closes #150
=> Add neo4j support

src/main/java/io/github/jhipster/online/web/rest/GitResource.java
=> add user-agent header in the POST API call to Gitlab

src/main/webapp/app/account/password-reset/init/password-reset-init.component.html, src/main/webapp/app/account/password-reset/init/password-reset-init.component.ts, src/main/webapp/app/account/register/register.component.ts, src/main/webapp/app/admin/user-management/user-management.component.html, src/main/webapp/app/admin/user-management/user-management.component.ts
This removes the `mailEnabled` property from the front end. 
Fixes https://github.com/jhipster/jhipster-online/issues/166
=> Fix for Email Sending Funcationality

pom.xml, src/main/java/io/github/jhipster/online/domain/GitCompany.java, src/main/java/io/github/jhipster/online/domain/deserializer/YoRCDeserializer.java, src/main/java/io/github/jhipster/online/service/CiCdService.java, src/main/java/io/github/jhipster/online/service/GitService.java, src/main/java/io/github/jhipster/online/service/GithubService.java, src/main/java/io/github/jhipster/online/service/GitlabService.java, src/main/java/io/github/jhipster/online/service/JdlService.java, src/main/java/io/github/jhipster/online/service/dto/GitConfigurationDTO.java, src/main/java/io/github/jhipster/online/web/rest/GitResource.java, src/main/resources/logback-spring.xml, src/main/webapp/app/home/home.scss, src/main/webapp/content/css/loading.css
This fixes some compiler warnings related to logs and refactors some code. This is part of trying to fix https://github.com/jhipster/jhipster-online/issues/184. 
Related to https://github.com/jhipster/jhipster-online/issues/184
=> Fix Some Compiler Warnings, Exceptions and Refactor Code

src/main/java/io/github/jhipster/online/service/enums/CiCdTool.java, src/main/webapp/app/home/ci-cd/ci-cd.component.html
Reverts jhipster/jhipster-online#182
=> Revert "Add GitHub Actions and CircleCI for Continuous Integration"

src/main/java/io/github/jhipster/online/service/enums/CiCdTool.java, src/main/webapp/app/home/ci-cd/ci-cd.component.html
This adds Github Actions to the Continuous Integration UI
Related to https://github.com/jhipster/jhipster-online/issues/163
=> Add GitHub Actions for Continuous Integration

.github/workflows/label-cleanup.yml
This adds a simple label remover for "status: " labels
Fixes https://github.com/jhipster/jhipster-online/issues/203
=> Add Auto Label Remover for Issues/Pull Requests

.github/release-drafter.yml, .github/workflows/release-drafter.yml
This adds a release drafter configuration just to make a simple release note flow.
Fixes #198
=> Add Release Drafter Configuration

.github/workflows/github-ci.yml, pom.xml, src/main/java/io/github/jhipster/online/web/rest/GitResource.java
This updates the project to Java 11 and fixes the problematic Git sync issues using the newer HttpClient libraries.
Fixes https://github.com/jhipster/jhipster-online/issues/200 and Related to https://github.com/jhipster/jhipster-online/issues/93
=> Upgrade to Java 11 and Fix Problematic Git Sync

src/main/webapp/app/home/generator/generator.component.html
This seems not to be updated after around https://github.com/jhipster/generator-jhipster/commit/f26c0cf83fa07286d94c263bb1db801779642d9f. Hence I am updating this to match the generator CLI.
Fixes https://github.com/jhipster/jhipster-online/issues/189
=> Update No Database Visibility Condition

src/main/java/io/github/jhipster/online/config/MDCConfiguration.java, src/main/java/io/github/jhipster/online/mdc/logging/MDCInterceptor.java, src/main/java/io/github/jhipster/online/service/GithubService.java, src/main/resources/logback-spring.xml
This adds an MDC interceptor for all logs related to `io.github.jhipster.online` package.
Related to https://github.com/jhipster/jhipster-online/pull/186#discussion_r456588221
=> Add MDC Interceptor for Logging

src/main/java/io/github/jhipster/online/util/SanitizeInputs.java, src/test/java/io/github/jhipster/online/util/SanitizeInputsTest.java
This uses the regex pre-compile instead of string matcher.
Related to #209
=> Use Regex Pre-compile Instead of String Matcher

src/main/java/io/github/jhipster/online/security/jwt/TokenProvider.java, src/main/java/io/github/jhipster/online/service/GithubService.java, src/main/java/io/github/jhipster/online/service/GitlabService.java, src/main/java/io/github/jhipster/online/service/JHipsterService.java, src/main/java/io/github/jhipster/online/service/JdlMetadataService.java, src/main/java/io/github/jhipster/online/service/JdlService.java, src/main/java/io/github/jhipster/online/service/UserService.java, src/main/java/io/github/jhipster/online/service/interfaces/GitProviderService.java, src/main/java/io/github/jhipster/online/web/rest/CiCdResource.java, src/main/java/io/github/jhipster/online/web/rest/GeneratorResource.java, src/main/java/io/github/jhipster/online/web/rest/GitResource.java, src/main/java/io/github/jhipster/online/web/rest/JdlResource.java, src/main/java/io/github/jhipster/online/web/rest/StatisticsResource.java, src/main/java/io/github/jhipster/online/web/rest/UserJWTController.java, src/test/java/io/github/jhipster/online/config/WebConfigurerTest.java, src/test/java/io/github/jhipster/online/repository/CustomAuditEventRepositoryIT.java, src/test/java/io/github/jhipster/online/security/jwt/JWTFilterTest.java, src/test/java/io/github/jhipster/online/security/jwt/TokenProviderTest.java, src/test/java/io/github/jhipster/online/service/MailServiceIT.java, src/test/java/io/github/jhipster/online/service/enums/TemporalValueTypeTest.java, src/test/java/io/github/jhipster/online/web/rest/AccountResourceIT.java
This fixes some remaining vulnerabilities and code smells.
Related to https://github.com/jhipster/jhipster-online/issues/209
=> Fix some Remaining Vulnerabilities and Code Smells

src/main/java/io/github/jhipster/online/web/rest/JdlResource.java, src/test/java/io/github/jhipster/online/util/SanitizeInputsTest.java
This adds jdl content to be sanitized before being processed.
Related to https://github.com/jhipster/jhipster-online/issues/209
=> Add jdl content to sanitization as well

src/main/java/io/github/jhipster/online/service/JHipsterService.java
This adds the generation process error stream to debug log since otherwise there's a possibility that the buffer gets filled up and blocks the generation process.
Reference: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Process.html (paragraph 3)
Related to #184 and Reverts #219
=> Add Generation Process Error Stream to Debug Log

Dockerfile, package.json, src/main/docker/Dockerfile, yarn.lock
This updates the jhipster generator to version 6.10.1
Fixes https://github.com/jhipster/jhipster-online/issues/228
=> Upgrade generator-jhipster version to 6.10.1

app.yaml
This was done to see if we could improve the load times of the pages.
Related to https://github.com/jhipster/jhipster-online/issues/230
=> Update memory of VM to 4GB

Dockerfile, src/main/docker/Dockerfile
=> Upgrade generator-jhipster@6.10.3

pom.xml, src/main/java/io/github/jhipster/online/service/CiCdService.java, src/main/java/io/github/jhipster/online/service/JHipsterService.java
This upgrades to the process creation to ProcessBuilder and also upgrades the github-api
Related to https://github.com/jhipster/jhipster-online/issues/241
=> Upgrade Process to ProcessBuilder and upgrade github-api

Dockerfile, package.json, src/main/docker/Dockerfile, yarn.lock
This updates jhipster-generator to 6.10.4
=> Update jhipster-generator to 6.10.4

src/main/java/io/github/jhipster/online/config/WebConfigurer.java, src/main/java/io/github/jhipster/online/web/rest/errors/ExceptionTranslator.java
Related to https://github.com/jhipster/jhipster-online/issues/209
=> Refactor code to eliminate two minor sonar reported bugs

.github/workflows/github-ci.yml, .github/workflows/release-drafter.yml, CONTRIBUTING.md, README.md, src/main/java/io/github/jhipster/online/service/GithubService.java, src/main/java/io/github/jhipster/online/service/GitlabService.java, src/main/webapp/app/shared/git-provider/git-provider.component.ts, src/main/webapp/index.html
This renames all instances of master to main
Resolves https://github.com/jhipster/jhipster-online/issues/246
=> Rename all Instances of master to main

.github/workflows/github-ci.yml, package.json, src/main/java/io/github/jhipster/online/service/JdlMetadataService.java, src/test/java/io/github/jhipster/online/config/audit/AuditEventConverterTest.java, src/test/java/io/github/jhipster/online/service/JdlMetadataServiceTest.java, src/test/java/io/github/jhipster/online/web/rest/YoRCResourceIntTest.java
This adds prettier check to our continuous integration pipeline.
=> Add prettier check to CI

src/main/java/io/github/jhipster/online/config/SecurityConfiguration.java
Fixes https://github.com/jhipster/jhipster-online/issues/261
=> Add correct csp headers for google-analytics

src/main/resources/config/application-prod.yml
Fixes https://github.com/jhipster/jhipster-online/issues/266
=> Fix for Thymeleaf Template Error

src/main/webapp/index.html
I think we should enable service worker for better user experience. Not sure if there's a reason why this is disabled? 🤔
=> Enable service-worker.js

src/main/java/io/github/jhipster/online/service/CiCdService.java, src/main/java/io/github/jhipster/online/service/enums/CiCdTool.java
This corrects the name of the continuous integration tool for the bot generated pull request and commit.
Resolves https://github.com/jhipster/jhipster-online/issues/272
=> Correct Continous Integration Tool Name for Pull Request and Commit by bot

.github/workflows/copyright-update.yml
This updates some minor typos in the copyright update workflow.
Related to https://github.com/jhipster/jhipster-online/issues/276
=> Adjust some minor typos in copyright update workflow

src/main/webapp/app/entities/statistics/statistics.component.ts, src/main/webapp/app/entities/statistics/statistics.utils.ts, src/main/webapp/app/home/generator/generator.component.html, src/main/webapp/app/home/generator/generator.component.ts, src/main/webapp/app/home/generator/jhipster.configuration.model.ts
Related to https://github.com/jhipster/generator-jhipster/issues/13081
=> Remove UAA

src/main/webapp/app/home/generator/generator.component.html
Related to https://github.com/jhipster/generator-jhipster/issues/10575
=> V7 : add Vue option

src/main/java/io/github/jhipster/online/service/enums/CiCdTool.java, src/main/webapp/app/home/ci-cd/ci-cd.component.html
This is a duplicate of https://github.com/jhipster/jhipster-online/pull/182. 
Fixes https://github.com/jhipster/jhipster-online/issues/163
=> Add CircleCI for Continuous Integration

Dockerfile, package.json, pom.xml, src/main/docker/Dockerfile, yarn.lock
This prepares jhipster-online to be upgraded to the latest generator; v7
=> Upgrade to jhipster-generator v7.0.0

.github/workflows/deploy.yml
This migrates the docker image from container registry to artifact registry and fixes all errors related to deployment.
Resolve #285
=> Migrate docker image from container registry to artifact registry

.github/workflows/deploy.yml, src/main/java/io/github/jhipster/online/service/JHipsterService.java, src/test/java/io/github/jhipster/online/service/JHipsterServiceTest.java
These options are no longer supported by generator and seems to generate errors if added. The prettier transformation are done by default.
Resolve https://github.com/jhipster/jhipster-online/issues/287
=> Remove prettier-java and force-insights options

src/main/java/io/github/jhipster/online/service/JHipsterService.java, src/test/java/io/github/jhipster/online/service/JHipsterServiceTest.java
Disable statistics until https://github.com/jhipster/generator-jhipster/pull/14485 is merged and patch release is created. 
Related to https://github.com/jhipster/generator-jhipster/pull/14485.
=> Disable Statistice for Now

src/main/java/io/github/jhipster/online/service/JHipsterService.java
Related to https://github.com/jhipster/generator-jhipster/pull/14485
=> Add --force-insights option back

src/main/webapp/app/entities/statistics/statistics.component.html
Change the Angular/React labels to 'Client framework' as Jhipster
supports multiple frameworks now.
Please suggest if we can have a better word 😄
=> Change Client frameworks labels

src/main/java/io/github/jhipster/online/config/SecurityConfiguration.java, src/main/java/io/github/jhipster/online/web/rest/GeneratorResource.java, src/main/webapp/app/home/generator/generator.component.html, src/main/webapp/app/home/generator/generator.component.ts, src/main/webapp/app/home/generator/generator.route.ts, src/main/webapp/app/home/home.component.html, src/main/webapp/app/home/home.component.ts, src/main/webapp/app/home/welcome/welcome.component.html, src/main/webapp/app/home/welcome/welcome.component.ts
Remove security on "/download-application" and refactor user-interface
to allow non-logged in users to generate and download the zip file.
Fix #162
=> Allow anonymous users to download zipfile

Dockerfile, package.json, pom.xml, src/main/docker/Dockerfile, yarn.lock
Fix https://github.com/jhipster/jhipster-online/issues/303
=> Upgrade to generator-jhipster@7.1.0

Dockerfile
=> Bump to generator-jhipster@8.0.0-beta.2

package.json, pom.xml
=> Release v2.22.0

src/main/java/io/github/jhipster/online/JhonlineApp.java, src/main/webapp/app/blocks/interceptor/errorhandler.interceptor.ts, src/main/webapp/app/home/ci-cd/ci-cd.output.component.ts, src/main/webapp/app/home/generator/generator.output.component.ts, src/main/webapp/app/home/jdl-metadata/jdl-metadata.service.ts, src/main/webapp/app/home/jdl-metadata/jdl.output.component.ts, src/main/webapp/app/layouts/main/main.component.ts, src/main/webapp/app/layouts/profiles/profile.service.ts, src/main/webapp/index.html
Some fixes: https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster_jhipster-online
Before:
=> Sonar issues

src/main/webapp/app/home/home.component.html, src/main/webapp/app/home/home.component.ts
SHOULD NOT BE MERGED until @jdubois tag it as ready
=> chore: remove azure feature flag

src/main/webapp/app/home/home.component.ts
Fix: https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=jhipster_jhipster-online&open=AYqxrHKxpSNoNGCdyVA8 
Related to #413
=> Sonar: Remove this unused import of 'ActivatedRoute'

src/main/java/io/github/jhipster/online/config/SecurityConfiguration.java
Fix: https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster_jhipster-online&open=AYZvKabD5F7ovg0LDoJj
=> Sonar: Remove this use of 'featurePolicy'; it is deprecated

src/main/java/io/github/jhipster/online/config/SecurityConfiguration.java
Fix: https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster_jhipster-online&open=AYZvKabD5F7ovg0LDoJi
=> Sonar: Remove this use of 'WebSecurityConfigurerAdapter'; it is deprecated

src/main/webapp/app/home/jdl-metadata/jdl-studio.component.ts
Fix: https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster_jhipster-online&open=AXgerbBj-uCBXnhxiky9
=> Sonar: Update this function so that its implementation is not identical to the one on line 69

src/main/docker/sonar.yml
Related to https://github.com/jhipster/jhipster-online/issues/318
=> Remove unnecessary port mapping on sonar config

src/main/webapp/app/home/azure-generator/azure-generator.component.ts, src/main/webapp/app/home/generator/generator.component.html, src/main/webapp/app/home/generator/generator.component.ts, src/main/webapp/app/home/generator/generator.configuration.model.ts, src/main/webapp/app/home/generator/jhipster.configuration.model.ts
Support generate terraform and bicep scripts.
=> Support IaC tools for azure applications

src/main/webapp/app/home/welcome/welcome.component.html
@hangwan97 is this OK for you?
=> Update Azure Spring Apps to Azure Container Apps
